### ISSUE TITLE
请求接口时一直报错，

### ISSUE THREAD

**Issue by 8ku** [baidu/unit-dmkit#108]
bot_tokens.json已经把技能和API配置好了，请问这是什么原因呢？

input:
报关单号12312到哪了
Traceback (most recent call last):
  File "bot_emulator.py", line 97, in <module>
    main(sys.argv[1], sys.argv[2])
  File "bot_emulator.py", line 67, in main
    obj = requests.post(url, data=json.dumps(payload), headers=json_header).json()
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8010): Max retries exceeded with url: /search?access_token= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5318b5190>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by HuangLK** [comment]
先确认下dmkit服务是否正常运行
