### ISSUE TITLE
总是报告图形使用错误

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#37]
https://drive.google.com/file/d/1fcMVsnr7yJvz4Sol8dDJX8cBhH9cVRiT/view?usp=sharing
和
https://drive.google.com/file/d/16O8TwztQBKff7E2c7F2SdSS8kCQ_G7-q/view?usp=sharing
都会报错，已尝试删除部分但依旧未能解决问题

多次修改后还是出现问题
**xutongxin@xutongxin-virtual-machine:~/unit-dmkit/language_compiler$ sudo python run.py** 
Traceback (most recent call last):
  File "run.py", line 64, in <module>
    main()
  File "run.py", line 58, in main
    output_lines = compiler_function(input_lines)
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 341, in run
    ps = XmlParser(data)
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 71, in __init__
    self.__parse_cells() # parse every cell to extract info of node and arrow 
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 116, in __parse_cells
    raise Exception('wrong shape is used in cell with text: ', nlg)                    
Exception: ('wrong shape is used in cell with text: ', u'user_localtion,user_back,user_last')
**xutongxin@xutongxin-virtual-machine:~/unit-dmkit/language_compiler$ sudo python run.py** 
Traceback (most recent call last):
  File "run.py", line 64, in <module>
    main()
  File "run.py", line 58, in main
    output_lines = compiler_function(input_lines)
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 341, in run
    ps = XmlParser(data)
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 71, in __init__
    self.__parse_cells() # parse every cell to extract info of node and arrow 
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 116, in __parse_cells
    raise Exception('wrong shape is used in cell with text: ', nlg)                    
Exception: ('wrong shape is used in cell with text: ', u'user_version,kw_wanted')
**xutongxin@xutongxin-virtual-machine:~/unit-dmkit/language_compiler$ sudo python run.py** 
Traceback (most recent call last):
  File "run.py", line 64, in <module>
    main()
  File "run.py", line 58, in main
    output_lines = compiler_function(input_lines)
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 341, in run
    ps = XmlParser(data)
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 71, in __init__
    self.__parse_cells() # parse every cell to extract info of node and arrow 
  File "/home/xutongxin/unit-dmkit/language_compiler/compiler_xml.py", line 116, in __parse_cells
    raise Exception('wrong shape is used in cell with text: ', nlg)                    
Exception: ('wrong shape is used in cell with text: ', u'user_version')

**Comment by lyc-baidu** [comment]
部分圆角矩形没有填写“BOT”关键字
