### ISSUE TITLE
对话错误

### ISSUE THREAD

**Issue by Yecgaa1** [baidu/unit-dmkit#39]
Traceback (most recent call last):
  File "bot_emulator.py", line 97, in <module>
    main(sys.argv[1], sys.argv[2])
  File "bot_emulator.py", line 67, in main
    obj = requests.post(url, data=json.dumps(payload), headers=json_header).json()
  File "/home/xutongxin/.local/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/xutongxin/.local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/xutongxin/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xutongxin/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/xutongxin/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8010): Max retries exceeded with url: /search?access_token=····················································································（确定是access_token)(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f246d8e5490>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by lyc-baidu** [comment]
DM Kit服务是否已在本地正常启动？

**Comment by xutongxin** [comment]
我应该已经按照步骤一步步操作，但是似乎是没有开启，只是完成了编译，如何开启？
谢谢

**Comment by lyc-baidu** [comment]
在_build目录下运行./dmkit

**Comment by Yecgaa1** [comment]
谢谢
